@startuml

class Player {
    +weapon
    +choose_weapon(type)
}

class Weapon {
    RULES
    +type
    +beats?(other)
}

class Game {
    +players
    +{static} start(player1, player2)
    +{static} instant_access()
    +player1()
    +player2()
    +result()
}

Game -> Player :"2" players
Player -> Weapon : weapons

@enduml
