@startuml

class Player {
    +name
    +weapon=
    +points
    +a_computer?()
    +gain(points)
}

enum CompResult {
    BEATS
    DRAW
    LOSES
}

enum Weapon {
    ROCK
    PAPER
    SCISSORS

    RULES {}

    +{static} compare(weapon, other_weapon)
    +{static} random()
}

class Game {
    +result
    +{static} start(player1, player2)
    +{static} instant_access()
    +player1()
    +player2()
    +game_over?()
    +winner()
    -winning_players()
}

Game -> Player : +players[2]
Player -> Weapon : weapons

@enduml
